# Generated by Django 3.2.3 on 2021-06-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_id'),
        ('checkout', '0003_alter_order_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonlineitems', to='checkout.order')),
            ],
        ),
    ]
