# Generated by Django 3.2.3 on 2021-06-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_lessonlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlineitem',
            name='lesson_date',
        ),
    ]
