# Generated by Django 3.2.3 on 2021-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
