# Generated by Django 3.2.3 on 2021-07-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20210708_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=6, null=True),
        ),
    ]
