# Generated by Django 3.2.3 on 2021-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_alter_coach_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rating',
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
