# Generated by Django 3.2.3 on 2021-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_alter_coach_options'),
        ('lessons', '0004_alter_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.coach'),
        ),
    ]
