# Generated by Django 3.2.3 on 2021-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='coach',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
