# Generated by Django 3.2.3 on 2021-07-04 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0009_alter_lesson_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default='2021-09-05'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='spots',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
