# Generated by Django 3.2.3 on 2021-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=12345, max_length=254),
        ),
    ]
